### ISSUE TITLE
NS2+ + GunGame shotgun issue

### ISSUE THREAD

**Issue by ZycaR** [Mendasp/NS2Plus#18]
Hi Mendasp, thanks for quick reply !

I have another and probably last known issue (error in log) when running NS2+ with GunGame mode.
.. can you please add here an test whether `self:GetParent()` is not null ?

_lua/NS2Plus/Server/CHUD_ServerStats.lua:1265_
`local steamId = GetSteamIdForClientIndex(self:GetParent():GetClientIndex())`

Description:
GunGame mode is switching weapons as reward for killing the enemy. this means server switch gun once kill is registered by bullet. The issue occurs only on the shotgun, as it fires set of bullets and all of these "fired" bullets are evaluated. When shotgun lost it's parent player (it's dropped or destroyed) in middle of bullet evaluation array, the error is produced. self:GetParent() can result to nil.
Unfortunately GunGame mod do this directly by server side, but I can imagine future mods should do the same as it's easiest way to evaluate hits/kills. For you it's just one line of code (one condition in advance) for us it will be whole mechanism to delay switching weapons after all bullets are evaluated.

Thank you in advance .. and
Happy easter!!!

**Comment by Mendasp** [comment]
I added a check for the parent in most places where code like this is used, let me know if you still have problems with this. I just published it.

**Comment by ZycaR** [comment]
Will test it on Wooza's server (once applied) .. but as far as I can say (after several smoke tests to reproduce issues) seems they are all fixed. Thank you !

EDIT: Tested, and it looks ok :P you can close issue as fixed.
