### ISSUE TITLE
Remove outdated references

### ISSUE THREAD

**Issue by keatsandyeats** [Mendasp/NS2Plus#39]
The customization menu has a "Changelog" button that links to Mendasp's deprecated workshop mod: 
https://github.com/sclark39/NS2Plus/blob/master/lua/NS2Plus/Client/CHUD_MainMenu.lua#L324

Some configs are referenced using Mendasp's GitHub URL: 
https://github.com/sclark39/NS2Plus/blob/master/lua/NS2Plus/Shared/CHUD_Badges.lua#L1
https://github.com/sclark39/NS2Plus/blob/master/lua/NS2Plus/CHUD_Client.lua#L70

The main menu news page (this isn't displayed anymore) links to mendasp.net:
https://github.com/sclark39/NS2Plus/blob/master/lua/NS2Plus/Client/CHUDGUI_MenuNews.lua#L4

**Comment by GhoulofGSG9** [comment]
Thanks for this report. I cleaned up any old references for the next ns2+ update (version 371)
