### ISSUE TITLE
Various GUI options don't work properly

### ISSUE THREAD

**Issue by keatsandyeats** [Mendasp/NS2Plus#44]
I put these all in one issue because I assume these are all symptoms of an error with the GUIScript refactor (https://github.com/sclark39/NS2Plus/commit/37cb0c69e6f4b43cf8c31bc8a27c77ca15854632)

- `playercolor_m`, `playercolor_a`: custom minimap player colors do not work. (Also I think my custom color was changed, but i'm not sure.)
- `researchtimetooltip`: research time tooltips do not work for commanders (the tooltips work fine for specs)
- `mingui`: some minimal gui options don't take effect on connect, instead they only work after toggling mingui off/on:
  * smoke behind the map or tech buttons for alien comm 
  * scanlines behind the map or tech buttons for marine comm
  * smoke behind gorge build menu
- `friends`: remove friend highlighting doesn't work

**Comment by GhoulofGSG9** [comment]
I fixed the mini map related options and the tool tips in the beta branch.
