### ISSUE TITLE
Spectator research tooltips are too transparent

### ISSUE THREAD

**Issue by keatsandyeats** [Mendasp/NS2Plus#51]
As spectator, hovering over the research icons produces the correct tooltips, but they are very faint and hard to see.

Originally reported in https://github.com/sclark39/NS2Plus/issues/47

**Comment by GhoulofGSG9** [comment]
Thanks for creating a new ticket for that case. I totally overlooked it when fixing the script error. Will try to fix it for the next ns2+ build.
