### ISSUE TITLE
GUIInsight_OtherHealthbars.lua script error due to missing 'other' local

### ISSUE THREAD

**Issue by Salads** [Mendasp/NS2Plus#75]
https://gist.github.com/Salads/a6a0d9120274c54cab7c5f7e5093e98b

**Comment by Salads** [comment]
i cant find a declaration for otherList via github text search, probably it?

**Comment by GhoulofGSG9** [comment]
A few more details like a dump of your ns2+ settings and how the error occurred would help everybody else to fix this issue. I also edited the issue title to be more informative.

**Comment by Salads** [comment]
sorry i was drunk
where do i find the ns2+ settings

**Comment by GhoulofGSG9** [comment]
You can dump/export your ns2+ settings using the `plus_export` console command while ns2+ is loaded.

**Comment by Salads** [comment]
[ExportedSettings.txt](https://github.com/sclark39/NS2Plus/files/1754775/ExportedSettings.txt)
It happened when I was spectating waiting for a player slot to open up, and then I joined Marines. There were leftover health bars on the screen not attached to anything, and I couldn't move my mouse. After killing myself a couple times I was able to use my mouse to look around again.
