### ISSUE TITLE
Hive skill graph is not accurate

### ISSUE THREAD

**Issue by L-as** [Mendasp/NS2Plus#82]
The difference in skill between the teams is often heavily exaggerated in the hive skill graph

**Comment by GhoulofGSG9** [comment]
Please attach the LastRoundStats.json (from [~/.config, %appdata%]/Natural Selection 2/Ns2Plus/) to any report about issues of the end round stats.

**Comment by L-as** [comment]
I can't seem to reproduce this anymore, somehow.
