### ISSUE TITLE
Incorrect average skill computing

### ISSUE THREAD

**Issue by gogijan** [Mendasp/NS2Plus#9]
Player with nick 13 and hive skill 2201 joins alien side. Average alien skill before joining 1130, after join 969. This happens when the code assumes then new player skill is equals to zero.
Screenshots
http://images.akamai.steamusercontent.com/ugc/448455622240790244/64B03462192EE3B166FA2A6F06FC13D9ED25020E/
http://images.akamai.steamusercontent.com/ugc/448455622240810596/26CEECCB0CCDF607C74819B52511BECB05899D3E/
http://images.akamai.steamusercontent.com/ugc/448455622240810919/671CC9CDBD7EA5EEECD6CB95E20293041DEC6E08/

**Comment by Mendasp** [comment]
The code assumes nothing, the skill info is already part of the scoreboard info, if it can't fetch a player's Hive skill then it will be 0, but it has nothing to do with NS2+, it's a vanilla bug in any case.

**Comment by gogijan** [comment]
Maybe not take into account the player's skill until it is zero?

**Comment by Mendasp** [comment]
New players have a skill of 0. It's an issue with Hive's reliability, there's nothing for me to fix here.
